### PR TITLE
Change `Device("clifford")` to use `ErrorTrackingBackend` instead of `CircuitSimulator`

### PR DESCRIPTION
**Pull request by antalszava**
This PR updates the `Device("clifford")` user interface to use the error tracking backend in the background as it is more performant than simply using the tableau simulator implemented by `CircuitSimulator`.

The `CircuitSimulator` backend will no longer be advertised in the docs and it will be considered a private backend. Nonetheless, it is still available through `Device("tableau")` for testing purposes because the error tracker backend also uses `CircuitSimulator`.

----

Open question: `CircuitSimulator` offers the `after_reset` option to be set, which is not supported by the error tracking backend. Would this be something to support?

### CODE REVIEW

**Comment by massarom** [comment]
> `CircuitSimulator` offers the `after_reset` option to be set, which is not supported by the error tracking backend. Would this be something to support?

Don't think so, I think it was a quirk of `CircuitSimulator`. If someone wants to accumulate simulation results they can do it manually, no need to have special mechanisms in the API.

**Review by massarom — APPROVED** [review]

**Comment by massarom** [comment]
@antalszava this is only missing the fix for the failing test and then I think we're done!

**Comment by antalszava** [comment]
Just pushed some changes that passed locally.

Some notes:
* The docs will still occasionally use the "tableau" simulator to showcase that the internal quantum state can be returned at the cost of slower execution;
* Some outputs are dependent on seeding and were updated because the new simulator outputs different results that are still correct;
* Changed to use `plaquette.rng.integers` everywhere such that seeding can influence the entire simulator

**Comment by massarom** [comment]
In `conftest` there's a fixture called "stable_rgen" which looks like not being too stable.

It's using the wrong API I think, and I don't know how it went unnoticed for so long but basically L10 of `conftest` needs to be replaced by `np.random.default_rng(seed=123123456)`.

**Pull request merged**
